version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mateopdt2022
      MYSQL_DATABASE: gestion-utec
      MYSQL_USER: mateopdt
      MYSQL_PASSWORD: mateopdt2022
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: